---
- name: Install Apache
  hosts: vm1
  become: yes
  tasks:
  - name: Installing the latest version of Apache
    yum: pkg=httpd state=latest
  - name: Enabling it on System boot
    systemd: name=httpd enabled=yes
    notify:
    - start apache

  handlers:
    - name: start apache
      service: name=httpd state=started
