# An Ansible Playbook to delete a virtual machine using Azure Resource Manager
# Extra variables required when running the playbook:
#   - instance_name: a variable to get the name of virtual machine & it's corresponding resources
#   - admin_password_here: a variable to pass the password for virtual machine (VM)
#   - vm_image_offer: a variable to select the OS provider for VM. Example: Ubuntu, RHEL, CentOS
#   - vm_image_publisher: a variable to select the image publisher
#   - vm_sku_version: a variable to get the SKU version (corresponds to the image offer & publisher.)
#
# Variable to change: resource_group: change this variable to create your own resource group
#
# Command to run the playbook:
#     ansible-playbook create-vm.yml --extra-vars "admin_password_here=<enter preferred password here>"

- name: Create Azure VM
  hosts: localhost
  connection: local
  # Defining a global resource group name
  vars:
    resource_group: 'Paychex
    
  - name: Remove a VM and all resources that were autocreated
  azure_rm_virtualmachine:
    resource_group: {{ resource_group }}
    name: "{{ instance_name }}-vm"
    remove_on_absent: all_autocreated
    state: absent
