---
- hosts: vm2
  vars:
    mongoDB_Port: 4230

  tasks:
    - name: Adding MongoDB repository for CentOS
      copy: src="mongorepo.repo"
    - name: Checking if I can connect to the server.
      ping:
    - name: Installing MongoDB
      become: yes
      yum: name=mongodb-org state=present
