---
- hosts: vm2
  become: yes
  become_user: root
  vars:
    mongoDB_Port: 4230

  tasks:
    - name: Checking if I can connect to the server.
      ping:
    - name: Adding MongoDB repository for CentOS
      copy: src="mongorepo.repo" dest="/etc/yum.repos.d/mongodb-org-4.2.repo"
    - name: Installing MongoDB
      yum: name=mongodb-org state=present

      

