---
- hosts: vm3

  tasks:
    - name: Downloading vault
      unarchive:
        # TODO: Make the following link a variable dependent for the Vault version
        src: https://releases.hashicorp.com/vault/1.3.0/vault_1.3.0_linux_amd64.zip
        dest: /usr/bin
        remote_src: True
      become: yes
    
    #- name: Create vault config dir
