---
- hosts: Minecraft-vm
  become: yes
  become_user: root
  tasks:
    - name: Checking if I can connect to the server.
      ping:
    - name: Checking if Python3 is installed
      raw: test -e /usr/bin/python3
      changed_when: false
      failed_when: false
      register: check_python
    - name: Install Python
      raw: yum -y install python3
      when: check_python.rc != 0
      
    #Install unzip on server - I couldn't unarchive to work
    - name: Installing unzip
      raw: sudo apt install unzip
      
      #Create a minecraft directory
    - name: Create a Directory /home/vmadmin/Minecraft
      become: yes
      file:
        path: /home/vmadmin/Minecraft
        state: directory
        mode: 0771
        owner: 1000
        group: 1000
        
      #Download a the server files
    - name: Download Minecraft zip files
      become: yes
      get_url:
        url: https://minecraft.azureedge.net/bin-linux/bedrock-server-1.13.2.0.zip
        dest: /user/vmadmin/Minecraft/bedrock-server-1.13.2.0.zip
        mode: 0771
        owner: 1000
        group: 1000
    
    #Unzip the minecraft server files
    - name: Unzipping minecraft files
      raw: unzip bedrock-server-1.13.2.0.zip

    #Start the minecraft server   
    - name: Start minecraft server
      shell: LD_LIBRARY_PATH=. ./bedrock_server
        
        
        
#    - name: Extract Minecraft zip into /home/vmadmin/Minecraft
#      unarchive:
#        src: "/tmp/bedrock-server-1.13.2.0.zip"
#        dest: "/home/vmadmin/Minecraft"
#        remote_src: yes
    # TODO: Add check for requests
    #- name: Installing requests (pip library)
    #  shell: pip install requests
    #- name: Check if the minecraft download script exists
    #  stat:
    #    path: /home/vmadmin/Minecraft/download.py
    #  register: minecraft
    #- name: Create the file, if it doesnt exist already
    #  file:
    #    path: /home/vmadmin/Minecraft
    #    state: directory
    #    #shell: mkdir 
    #  when: minecraft.stat.exists == False 
    #- name: Adding Minecraft download file to VM3
    #  copy: src="download.py" dest="/home/vmadmin/Minecraft/"
    #  when: minecraft.stat.exists == False 
    #- name: PWD
    #  shell: 
    #    cmd: pwd
    # - name: Install minecraft server
    #  script: /home/vmadmin/Minecraft/download.py
    #  args:
    #    executable: python3
 
